#!/usr/bin/env sh

############################################################
#
# Regenerates the main memtech.website page from a template
#
# Note - all the dynamic content is done via JS now, not ruby
#
############################################################


INFILE="/home/dpritchett/sites/homepage.html"
OUTFILE="/var/www/html/index.html"

cp $INFILE $OUTFILE

echo main site index refreshed
